/*
 * This file is generated by jOOQ.
*/
package com.onevgo.jooq;


import com.onevgo.jooq.tables.TblDept;
import com.onevgo.jooq.tables.TblEmployee;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Default extends SchemaImpl {

    private static final long serialVersionUID = -81585216;

    /**
     * The reference instance of <code>default</code>
     */
    public static final Default DEFAULT = new Default();

    /**
     * The table <code>default.tbl_dept</code>.
     */
    public final TblDept TBL_DEPT = TblDept.TBL_DEPT;

    /**
     * The table <code>default.tbl_employee</code>.
     */
    public final TblEmployee TBL_EMPLOYEE = TblEmployee.TBL_EMPLOYEE;

    /**
     * No further instances allowed
     */
    private Default() {
        super("default", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            TblDept.TBL_DEPT,
            TblEmployee.TBL_EMPLOYEE);
    }
}
