/*
 * This file is generated by jOOQ.
*/
package com.onevgo.jooq;


import com.onevgo.jooq.tables.TblDept;
import com.onevgo.jooq.tables.TblEmployee;
import com.onevgo.jooq.tables.records.TblDeptRecord;
import com.onevgo.jooq.tables.records.TblEmployeeRecord;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships between tables of the <code>default</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<TblDeptRecord, Integer> IDENTITY_TBL_DEPT = Identities0.IDENTITY_TBL_DEPT;
    public static final Identity<TblEmployeeRecord, Integer> IDENTITY_TBL_EMPLOYEE = Identities0.IDENTITY_TBL_EMPLOYEE;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TblDeptRecord> KEY_TBL_DEPT_PRIMARY = UniqueKeys0.KEY_TBL_DEPT_PRIMARY;
    public static final UniqueKey<TblEmployeeRecord> KEY_TBL_EMPLOYEE_PRIMARY = UniqueKeys0.KEY_TBL_EMPLOYEE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<TblEmployeeRecord, TblDeptRecord> TBL_EMPLOYEE_IBFK_1 = ForeignKeys0.TBL_EMPLOYEE_IBFK_1;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<TblDeptRecord, Integer> IDENTITY_TBL_DEPT = createIdentity(TblDept.TBL_DEPT, TblDept.TBL_DEPT.ID);
        public static Identity<TblEmployeeRecord, Integer> IDENTITY_TBL_EMPLOYEE = createIdentity(TblEmployee.TBL_EMPLOYEE, TblEmployee.TBL_EMPLOYEE.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<TblDeptRecord> KEY_TBL_DEPT_PRIMARY = createUniqueKey(TblDept.TBL_DEPT, "KEY_tbl_dept_PRIMARY", TblDept.TBL_DEPT.ID);
        public static final UniqueKey<TblEmployeeRecord> KEY_TBL_EMPLOYEE_PRIMARY = createUniqueKey(TblEmployee.TBL_EMPLOYEE, "KEY_tbl_employee_PRIMARY", TblEmployee.TBL_EMPLOYEE.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<TblEmployeeRecord, TblDeptRecord> TBL_EMPLOYEE_IBFK_1 = createForeignKey(Keys.KEY_TBL_DEPT_PRIMARY, TblEmployee.TBL_EMPLOYEE, "tbl_employee_ibfk_1", TblEmployee.TBL_EMPLOYEE.D_ID);
    }
}
