/*
 * This file is generated by jOOQ.
*/
package com.onevgo.jooq;


import com.onevgo.jooq.tables.TblDept;
import com.onevgo.jooq.tables.TblEmployee;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in default
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>default.tbl_dept</code>.
     */
    public static final TblDept TBL_DEPT = TblDept.TBL_DEPT;

    /**
     * The table <code>default.tbl_employee</code>.
     */
    public static final TblEmployee TBL_EMPLOYEE = TblEmployee.TBL_EMPLOYEE;
}
