/*
 * This file is generated by jOOQ.
*/
package com.onevgo.jooq.tables;


import com.onevgo.jooq.Default;
import com.onevgo.jooq.Keys;
import com.onevgo.jooq.tables.records.TblEmployeeRecord;
import org.jooq.*;
import org.jooq.impl.TableImpl;

import javax.annotation.Generated;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblEmployee extends TableImpl<TblEmployeeRecord> {

    private static final long serialVersionUID = -69122684;

    /**
     * The reference instance of <code>default.tbl_employee</code>
     */
    public static final TblEmployee TBL_EMPLOYEE = new TblEmployee();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TblEmployeeRecord> getRecordType() {
        return TblEmployeeRecord.class;
    }

    /**
     * The column <code>default.tbl_employee.id</code>.
     */
    public final TableField<TblEmployeeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>default.tbl_employee.last_name</code>.
     */
    public final TableField<TblEmployeeRecord, String> LAST_NAME = createField("last_name", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>default.tbl_employee.gender</code>.
     */
    public final TableField<TblEmployeeRecord, String> GENDER = createField("gender", org.jooq.impl.SQLDataType.CHAR.length(1), this, "");

    /**
     * The column <code>default.tbl_employee.email</code>.
     */
    public final TableField<TblEmployeeRecord, String> EMAIL = createField("email", org.jooq.impl.SQLDataType.VARCHAR.length(255), this, "");

    /**
     * The column <code>default.tbl_employee.d_id</code>.
     */
    public final TableField<TblEmployeeRecord, Integer> D_ID = createField("d_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>default.tbl_employee.emp_status</code>.
     */
    public final TableField<TblEmployeeRecord, String> EMP_STATUS = createField("emp_status", org.jooq.impl.SQLDataType.VARCHAR.length(11), this, "");

    /**
     * Create a <code>default.tbl_employee</code> table reference
     */
    public TblEmployee() {
        this("tbl_employee", null);
    }

    /**
     * Create an aliased <code>default.tbl_employee</code> table reference
     */
    public TblEmployee(String alias) {
        this(alias, TBL_EMPLOYEE);
    }

    private TblEmployee(String alias, Table<TblEmployeeRecord> aliased) {
        this(alias, aliased, null);
    }

    private TblEmployee(String alias, Table<TblEmployeeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Default.DEFAULT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TblEmployeeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TBL_EMPLOYEE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TblEmployeeRecord> getPrimaryKey() {
        return Keys.KEY_TBL_EMPLOYEE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TblEmployeeRecord>> getKeys() {
        return Arrays.<UniqueKey<TblEmployeeRecord>>asList(Keys.KEY_TBL_EMPLOYEE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<TblEmployeeRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<TblEmployeeRecord, ?>>asList(Keys.TBL_EMPLOYEE_IBFK_1);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblEmployee as(String alias) {
        return new TblEmployee(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TblEmployee rename(String name) {
        return new TblEmployee(name, null);
    }
}
