/*
 * This file is generated by jOOQ.
*/
package com.onevgo.jooq.tables.records;


import com.onevgo.jooq.tables.TblDept;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TblDeptRecord extends UpdatableRecordImpl<TblDeptRecord> implements Record2<Integer, String> {

    private static final long serialVersionUID = 1250310209;

    /**
     * Setter for <code>default.tbl_dept.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>default.tbl_dept.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>default.tbl_dept.dept_name</code>. 部门名称
     */
    public void setDeptName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>default.tbl_dept.dept_name</code>. 部门名称
     */
    public String getDeptName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Integer, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TblDept.TBL_DEPT.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return TblDept.TBL_DEPT.DEPT_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getDeptName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblDeptRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblDeptRecord value2(String value) {
        setDeptName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TblDeptRecord values(Integer value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TblDeptRecord
     */
    public TblDeptRecord() {
        super(TblDept.TBL_DEPT);
    }

    /**
     * Create a detached, initialised TblDeptRecord
     */
    public TblDeptRecord(Integer id, String deptName) {
        super(TblDept.TBL_DEPT);

        set(0, id);
        set(1, deptName);
    }
}
